spring.application.name=batik-pedia-restful-api
spring.datasource.username=batik-pedia
spring.datasource.password=batik-pedia
spring.datasource.url=jdbc:postgresql://localhost:5432/batik-pedia
spring.jpa.hibernate.ddl-auto=update